# Generated by Django 5.0.4 on 2024-05-21 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0005_cart_total_price_alter_cart_product_alter_cart_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("address_2", models.CharField(blank=True, max_length=200, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("district", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cancelled", "Cancelled"),
                            ("paid", "Paid"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("received", "Received"),
                            ("returned", "Returned"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("items", models.ManyToManyField(to="orders.orderitem")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "VALID"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                            ("UNATTEMPTED", "UNATTEMPTED"),
                            ("EXPIRED", "EXPIRED"),
                            ("REFUNDED", "REFUNDED"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("sessionkey", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gateway_page_url",
                    models.URLField(blank=True, max_length=300, null=True),
                ),
                ("tran_date", models.DateTimeField(blank=True, null=True)),
                ("val_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bank_tran_id",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "store_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_refund", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
        ),
    ]
