# Generated by Django 5.0.4 on 2024-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
